# arxivの学問領域の指定
subject: 'cat:cs.SD OR cat:cs.AI OR cat:stat.ME OR cat:stat.OT OR cat:stat.ML OR cat:eess.AS'

# 検索キーワード
keywords:
        sound: 1
        audio: 1
        sound feature: 3
        audio feature: 3
        noise removal: 2
        spectrogram: 3

# 通知の閾値
score_threshold: 1
